"""empty message

Revision ID: 5867e780f712
Revises: None
Create Date: 2016-05-17 04:40:55.511297

"""

# revision identifiers, used by Alembic.
revision = '5867e780f712'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
